config/routes.rb
Kpt::Application.routes.draw do
  resources :tries

  resources :problems

  resources :keeps

  resources :boards

  devise_for :users
  root :to => "boards#index"

end

app/models/keep.rb
class Keep < ActiveRecord::Base
  # Associations
  belongs_to :board
  belongs_to :user
end

app/controllers/keeps_controller.rb
class KeepsController < ApplicationController
  # GET /keeps
  # GET /keeps.xml
  def index
    @keeps = Keep.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @keeps }
    end
  end

  # GET /keeps/1
  # GET /keeps/1.xml
  def show
    @keep = Keep.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @keep }
    end
  end

  # GET /keeps/new
  # GET /keeps/new.xml
  def new
    @keep = Keep.new
    col_select
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @keep }
    end
  end

  # GET /keeps/1/edit
  def edit
    @keep = Keep.find(params[:id])
    col_select
  end

  # POST /keeps
  # POST /keeps.xml
  def create
    @keep = Keep.new(params[:keep])

    respond_to do |format|
      if @keep.save
        format.html { redirect_to(@keep, :notice => 'Keep was successfully created.') }
        format.xml  { render :xml => @keep, :status => :created, :location => @keep }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @keep.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /keeps/1
  # PUT /keeps/1.xml
  def update
    @keep = Keep.find(params[:id])

    respond_to do |format|
      if @keep.update_attributes(params[:keep])
        format.html { redirect_to(@keep, :notice => 'Keep was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @keep.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /keeps/1
  # DELETE /keeps/1.xml
  def destroy
    @keep = Keep.find(params[:id])
    @keep.destroy

    respond_to do |format|
      format.html { redirect_to(keeps_url) }
      format.xml  { head :ok }
    end
  end

  private
  def col_select
    @boards = Board.all
    @users = User.all
  end
end

app/helpers/keeps_helper.rb
module KeepsHelper
end

app/views/keeps/_form.html.erb
<%= form_for(@keep) do |f| %>
  <% if @keep.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keep.errors.count, "error") %> prohibited this keep from being saved:</h2>

      <ul>
      <% @keep.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :board_id %><br />
    <%= f.collection_select(:board_id,@boards,:id,:name) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select(:user_id,@users,:id,:user_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keeps/edit.html.erb
<h1>Editing keep</h1>

<%= render 'form' %>

<%= link_to 'Show', @keep %> |
<%= link_to 'Back', keeps_path %>

app/views/keeps/index.html.erb
<h1>Listing keeps</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Board</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @keeps.each do |keep| %>
  <tr>
    <td><%= keep.title %></td>
    <td><%= keep.content %></td>
    <td><%= keep.board.name %></td>
    <td><%= keep.user.user_name %></td>
    <td><%= link_to 'Show', keep %></td>
    <td><%= link_to 'Edit', edit_keep_path(keep) %></td>
    <td><%= link_to 'Destroy', keep, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Keep', new_keep_path %>

app/views/keeps/new.html.erb
<h1>New keep</h1>

<%= render 'form' %>

<%= link_to 'Back', keeps_path %>

app/views/keeps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @keep.title %>
</p>

<p>
  <b>Content:</b>
  <%= @keep.content %>
</p>

<p>
  <b>Board:</b>
  <%= @keep.board.name %>
</p>

<p>
  <b>User:</b>
  <%= @keep.user.user_name %>
</p>


<%= link_to 'Edit', edit_keep_path(@keep) %> |
<%= link_to 'Back', keeps_path %>