config/routes.rb
Kpt::Application.routes.draw do
  resources :tries

  resources :problems

  resources :keeps

  resources :boards

  devise_for :users
  root :to => "boards#index"

end

app/models/try.rb
class Try < ActiveRecord::Base
end

app/controllers/tries_controller.rb
class TriesController < ApplicationController
  # GET /tries
  # GET /tries.xml
  def index
    @tries = Try.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tries }
    end
  end

  # GET /tries/1
  # GET /tries/1.xml
  def show
    @try = Try.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @try }
    end
  end

  # GET /tries/new
  # GET /tries/new.xml
  def new
    @try = Try.new
    col_select

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @try }
    end
  end

  # GET /tries/1/edit
  def edit
    @try = Try.find(params[:id])
    col_select
  end

  # POST /tries
  # POST /tries.xml
  def create
    @try = Try.new(params[:try])

    respond_to do |format|
      if @try.save
        format.html { redirect_to(@try, :notice => 'Try was successfully created.') }
        format.xml  { render :xml => @try, :status => :created, :location => @try }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @try.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tries/1
  # PUT /tries/1.xml
  def update
    @try = Try.find(params[:id])

    respond_to do |format|
      if @try.update_attributes(params[:try])
        format.html { redirect_to(@try, :notice => 'Try was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @try.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tries/1
  # DELETE /tries/1.xml
  def destroy
    @try = Try.find(params[:id])
    @try.destroy

    respond_to do |format|
      format.html { redirect_to(tries_url) }
      format.xml  { head :ok }
    end
  end

  private
  def col_select
    @boards = Board.all
    @users = User.all
  end
end

app/helpers/tries_helper.rb
module TriesHelper
end

app/views/tries/_form.html.erb
<%= form_for(@try) do |f| %>
  <% if @try.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@try.errors.count, "error") %> prohibited this try from being saved:</h2>

      <ul>
      <% @try.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :board_id %><br />
    <%= f.collection_select(:board_id, @boards,:id,:name) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select(:user_id, @users,:id,:user_name) %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.date_select :due_date %>
  </div>
  <div class="field">
    <%= f.label :assigned_user_id %><br />
    <%= f.text_field :assigned_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tries/edit.html.erb
<h1>Editing try</h1>

<%= render 'form' %>

<%= link_to 'Show', @try %> |
<%= link_to 'Back', tries_path %>

app/views/tries/index.html.erb
<h1>Listing tries</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Board</th>
    <th>User</th>
    <th>Due date</th>
    <th>Assigned user</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tries.each do |try| %>
  <tr>
    <td><%= try.title %></td>
    <td><%= try.content %></td>
    <td><%= try.board_id %></td>
    <td><%= try.user_id %></td>
    <td><%= try.due_date %></td>
    <td><%= try.assigned_user_id %></td>
    <td><%= link_to 'Show', try %></td>
    <td><%= link_to 'Edit', edit_try_path(try) %></td>
    <td><%= link_to 'Destroy', try, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Try', new_try_path %>

app/views/tries/new.html.erb
<h1>New try</h1>

<%= render 'form' %>

<%= link_to 'Back', tries_path %>

app/views/tries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @try.title %>
</p>

<p>
  <b>Content:</b>
  <%= @try.content %>
</p>

<p>
  <b>Board:</b>
  <%= @try.board_id %>
</p>

<p>
  <b>User:</b>
  <%= @try.user_id %>
</p>

<p>
  <b>Due date:</b>
  <%= @try.due_date %>
</p>

<p>
  <b>Assigned user:</b>
  <%= @try.assigned_user_id %>
</p>


<%= link_to 'Edit', edit_try_path(@try) %> |
<%= link_to 'Back', tries_path %>