config/routes.rb
Kpt::Application.routes.draw do
  resources :tries

  resources :problems

  resources :keeps

  resources :boards

  devise_for :users
  root :to => "boards#index"

end

app/models/board.rb
class Board < ActiveRecord::Base
  # Associations
  has_and_belongs_to_many :users
  has_many :keeps
  has_many :problems
  has_many :tries


  # Validations
  validates :name, :presence => true
  validates :kpt_date, :presence => true
end

app/controllers/boards_controller.rb
# -*- coding: utf-8 -*-
class BoardsController < ApplicationController
  # 認証フィルター
  before_filter :authenticate_user!

  # GET /boards
  # GET /boards.xml
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.xml
  def show
    @board = Board.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.xml
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.xml
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to(@board, :notice => 'Board was successfully created.') }
        format.xml  { render :xml => @board, :status => :created, :location => @board }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.xml
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to(@board, :notice => 'Board was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.xml
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to(boards_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :kpt_date %><br />
    <%= f.date_select :kpt_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Kpt date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @boards.each do |board| %>
  <tr>
    <td><%= board.name %></td>
    <td><%= board.kpt_date %></td>
    <td><%= link_to 'Show', board %></td>
    <td><%= link_to 'Edit', edit_board_path(board) %></td>
    <td><%= link_to 'Destroy', board, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @board.name %>
</p>

<p>
  <b>Kpt date:</b>
  <%= @board.kpt_date %>
</p>

<hr/>
<h3>Keeps</h3>
<%= link_to 'New', new_keep_path %>
<table>
<% @board.keeps.each do |keep| %>
  <tr>
    <td><%= keep.title %></td>
    <td><%= link_to 'Show', keep %></td>
  </tr>
<% end %>
</table>

<hr/>
<h3>Problems</h3>
<%= link_to 'New', new_problem_path %>
<table>
<% @board.problems.each do |problem| %>
  <tr>
    <td><%= problem.title %></td>
    <td><%= link_to 'Show', problem %></td>
  </tr>
<% end %>
</table>

<hr/>
<h3>Tries</h3>
<%= link_to 'New', new_try_path %>
<table>
<% @board.tries.each do |try| %>
  <tr>
    <td><%= try.title %></td>
    <td><%= link_to 'Show', try %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>